align_steps: 500000
batch_size: 256
buffer_size: 2000000
critic_layernorm: true
device: cuda
discount: 0.99
distance_beta: 1.0
end_steps: 100000
end_threshold: 0.04
env: halfcheetah-medium-v2
eval_freq: 1000
explore_noise: 0.1
json_load: true
lmbda: 1.0
load_model: ''
log_freq: 5000
loss_tau: 0.7
n_episodes: 10
noise_clip: 0.5
normalize: true
normalize_reward: false
offline_alg: TD3_BC
online_steps: 100000
ope_steps: 500000
policy_freq: 2
policy_lr: 0.0001
policy_noise: 0.2
qf_lr: 0.0003
rb_load: half
refer_with_optimal_pi: true
save_dir: ./log
tau: 0.005
threshold: 0.0025
update_n: 1
warmup_steps: 1000
